---
- hosts:
  - swarm_manager
  - swarm_workers

  tasks:

    - name: Download Docker GPG key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /tmp/dockerkey.gpg
        validate_certs: no
        headers:
          Accept: '*/*'
      become: yes

    - name: Add Docker key repo
      apt_key:
        file: /tmp/dockerkey.gpg
        state: present
      become: yes


    - name: Install repo Docker
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
        state: present
      become: yes


    - name: Install Docker
      apt:
        name: ["docker-ce", "docker-ce-cli", "containerd.io"]
        update_cache: yes
        state: latest
      become: yes

    - name: Install Docker SDK python
      pip:
        name: docker
        state: present
      become: yes